apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: demo-sgp
  namespace: demo
spec:
  podSelector:
    matchLabels:
      app: spring
  securityGroups:
    groupIds:
      - sg-05698b10291227eae
      - sg-0118babf1bc154066

